package wiles.parser.enums;

public enum StatementFactoryTypes {
    TOP_LEVEL_EXPRESSION, DEFAULT_EXPRESSION_NO_CODE_BLOCK, DECLARATION_STATEMENT, METHOD_STATEMENT, LIST_STATEMENT,
    FOR_STATEMENT, RETURN_STATEMENT, WHEN_STATEMENT, WHILE_STATEMENT, BREAK_STATEMENT, CONTINUE_STATEMENT,
}
