package wiles.parser.enums;

public enum StatementFactoryTypes {
    TOP_LEVEL_EXPRESSION, DEFAULT_EXPRESSION_NO_CODE_BLOCK, DECLARATION_STATEMENT, METHOD_STATEMENT, CONTINUE_STATEMENT,
    FOR_STATEMENT, RETURN_STATEMENT, IF_STATEMENT, WHILE_STATEMENT, BREAK_STATEMENT, LIST_STATEMENT, WHEN_STATEMENT,
    DICT_STATEMENT, TYPE_DEFINITION_STATEMENT
}
